### ISSUE TITLE
Test mmeta V3.0（minimum）

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#19]
# Purpose
Basic check : mmeta V3.0 package hosted on `V3.0_dev` branch

# Dependent task
* Develop *.Rd files for exported functions

# Tasks

- [x] install package hosted on  `V3.0_dev`   using `devtools::install_github()` function

  -  uninstall the current version and restart R session before each installation

- [x] User acceptance test using the examples shown in 
  -  [Single Table](https://docs.google.com/document/d/18Uque2u0FP_Od4I3f7aBlfQ9-nvZEdzy/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true)

  - [Multiple Table](https://docs.google.com/document/d/19ywXMfYUZ4zCBrVbZo3HHJPpEXa6eq5k/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true)

- [x] Explore `devtools::check_built()` and `devtools::check()` function

- [x] Check the package hosted on `V3.0_dev` using `devtools::check_built()` or `devtools::check()` function

**Comment by esuxiao** [comment]
@jchen1992 Hi Jiajie, you may add the checking error output here because they are parts of this issue. A good way to organize those notes and information is to put things which are associated with each other together.
