### ISSUE TITLE
Resolve the issues caused by C

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#2]
## Background

The primary cause to make mmeta V2.3 removed from CRAN was the following warnings: 
Found the following significant warnings:
     arms-R.c:87:16: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
     arms-R.c:844:16: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

https://github.com/esuxiao/mmeta/blob/13cab625ebbe12d00307929d30a825048fc5d23b/src/arms-R.c#L87
https://github.com/esuxiao/mmeta/blob/13cab625ebbe12d00307929d30a825048fc5d23b/src/arms-R.c#L844

## To do

- [x] Remove `display` function
- [x] Resolve the issues caused by `u_random()`

**Comment by esuxiao** [comment]
## Status update: 

Jiajie resubmitted the branch to CRAN on 2022/11/07: 
- Pass automatic check of CRAN
- Failed in manual review from Victoria Wimmer


## New issues raised by review comments

- [ ]  use the Authors@R field and declare Maintainer, Authors and Contributors with their appropriate roles with person() calls. 

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/DESCRIPTION#L6

- [ ]  And add add authors of HI package .

- [ ]  And add add authors of HI package .

- [ ] Copyrights —---- add authors of arms-R.c as ctb. 

- [ ]  Add more details about the package functionality and implemented methods

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/DESCRIPTION#L8

- [ ] add references in the description field of the DESCRIPTION file in the form:

1. authors (year) <doi:...>
2. authors (year) <arXiv:...>
3. authors (year, ISBN:...) 

- [ ]  Add `\value` to .Rd files regarding exported methods and explain the functions results in the documentation. Write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g.  `\value{No return value, called for side effects}` or similar)

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/man/plot.multipletables.rd#L46

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/man/plot.singletable.rd#L31

- [ ] You write information messages to the console that cannot be easily suppressed. It is more R like to generate objects that can be used to extract the information a user is interested in, and then print() that object.Instead of print()/cat() rather use message()/warning()  or if(verbose)cat(..) (or maybe stop()) if you really have to write text to the console.(except for print, summary, interactive functions) 

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/multiple.r#L58

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/multipleplot.r#L62

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/single.r#L15

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/singleplot.r#L93

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/summary.r#L67

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/summary.r#L108

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/summary.r#L109

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/summary.r#L110

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/summary.r#L111

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/summary.r#L112

- [ ] Omit any default path in writing functions.  examples/vignettes/tests you can write to tempdir(). e.g.: R/multipleplot.r ; R/singleplot.r   Do not change the user's options, par or working directory. If you really have to do so within functions, please ensure with an *immediate* call of on.exit() that the settings are reset when the function is exited. e.g.:R/multipleplot.r ; R/singleplot.r

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/singleplot.r#L63

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/singleplot.r#L155

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/multipleplot.r#L110

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/multipleplot.r#L187

https://github.com/esuxiao/mmeta/blob/49e3d60aca83559694dddd96406881eff2041c9e/R/multipleplot.r#L285


## To-do
- Create new subbranch hotfix_2.3_Wimmer to fix the issue
- [ ] Address the above review comments.
- [ ] Write resubmission comments:
* Have the issues why your package was archived been fixed?
* explain in the submission comments what you did about the review comments
- [ ] Resubmission to CRAN
