### ISSUE TITLE
Release V3.0(minimum) beta in GitHub

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#20]
# Dependent Task
* Test V3.0(minimum)

# Tasks

- [x] Merge `V3.0_dev` to main
- [x] Release mmeta V3.0 alpha in GitHub
- [x] Explore the functions in `devtools` to releasing package to CRAN, such as
  - `release`
  - `use_release_issue`
