### ISSUE TITLE
Address review comments from Benjamin Altmann

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#6]
## Status update

Jiajie addressed the review comments from Wimmer and resubmitted V2.4 to CRAN on 2022/12/02:

- Pass automatic check of CRAN

- Failed in manual review from Benjamin Altmann

## New issues raised by review comments

- [x] put references in the description

- [x] Author@R' -> 'Authors@R
- [x] Ensure that we do not change the user's options, par or working directory. Use on.exit() function before change par. Add the following lines of code at the beginning of the functions. 
```
<plot_function> <- function(){
   oldpar <- par(no.readonly = TRUE) # code line i
   on.exit(par(oldpar)) # code line i + 1
   …
   return()
}

```
https://github.com/esuxiao/mmeta/blob/d285cc22f52d8ac0939973fe87003abc030f2d07/R/multipleplot.r#L105

https://github.com/esuxiao/mmeta/blob/d285cc22f52d8ac0939973fe87003abc030f2d07/R/multipleplot.r#L169

https://github.com/esuxiao/mmeta/blob/d285cc22f52d8ac0939973fe87003abc030f2d07/R/multipleplot.r#L255

https://github.com/esuxiao/mmeta/blob/d285cc22f52d8ac0939973fe87003abc030f2d07/R/singleplot.r#L55

- [x] Please always make sure to reset to user's options(), working directory or par() after you changed it in examples and vignettes and demos.

```
oldpar <- par(no.readonly = TRUE)
<plot function call, such as 
plot(single.OR.Jeffreys, type="overlap", xlim=c(0.5, 2),
    main="Jefferys Prior")
>
par(oldpar)
```
https://github.com/esuxiao/mmeta/blob/d285cc22f52d8ac0939973fe87003abc030f2d07/man/plot.singletable.rd#L95

## To-do
 

- [x] Address the above review comments.

- [x]  Write resubmission comments:

- Have the issues why your package was archived been fixed? explain in the submission comments what you did about the review comments

 - Resubmission to CRAN
