### ISSUE TITLE
Create new branch V3.0_dev for further dev

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#9]
# Background

The existing version (V2.4)  has a lot of problems:

- bad design
- bad coding style
- inconsistent naming convention
- bad readability 

# Purpose
Create new branch to `V3.0_dev` to refactor the mmeta package

# Task

- [x] Create new branch to `V3.0_dev` 
- [x] Update the functions which are ready for release to dev
- [x] Delete deprecated *.Rd files
- [x] Update DESCRIPTION file
- [x] Update NAMESPACE file
